name: form_inputs
description: A simple in memory cache made for dart
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  formz: ^0.4.1

dev_dependencies:
  test: ^1.21.3
  very_good_analysis: ^3.0.1